export const GET_TEACHERS = 'GET_TEACHERS';
export const REMOVE_TEACHER = 'REMOVE_TEACHER';
export const ADD_TEACHER = 'ADD_TEACHER';
export const EDIT_TEACHER = 'EDIT_TEACHER';

export const GET_DEPARTMENTS = 'GET_DEPARTMENTS';
export const REMOVE_DEPARTMENT = 'REMOVE_DEPARTMENT';
export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const EDIT_DEPARTMENT = 'EDIT_DEPARTMENT';